src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NewsRepository::class)]
class News
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_news = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $body = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $link = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getDateNews(): ?\DateTime
    {
        return $this->date_news;
    }

    public function setDateNews(\DateTime $date_news): static
    {
        $this->date_news = $date_news;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): static
    {
        $this->body = $body;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): static
    {
        $this->link = $link;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }
}

src/Form/NewsForm.php
<?php

namespace App\Form;

use App\Entity\News;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;




class NewsForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('author')
            ->add('date_news', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date',
            ])
            ->add('body')
            ->add('link')
            ->add('title')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => News::class,
        ]);
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\News;
use App\Form\NewsForm;
use App\Repository\NewsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use DateTime;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;


#[IsGranted('IS_AUTHENTICATED_FULLY')]
#[Route('/news')]
final class NewsController extends AbstractController
{
    #[Route(name: 'app_news_index', methods: ['GET', 'POST'])]
    public function index(Request $request, EntityManagerInterface $entityManager, NewsRepository $newsRepository): Response
    {
        $news = new News();
        $news->setDateNews(new DateTime());
        $form = $this->createForm(NewsForm::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($news);
            $entityManager->flush();

            return $this->redirectToRoute('app_news_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('news/index.html.twig', [
            'news' => $newsRepository->findAll(),
            'form' => $form->createView(),
        ]);
    }


    #[Route('/new', name: 'app_news_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $news = new News();
        $news->setDateNews(new DateTime());
        $news->setDateNews(new DateTime()); 
        $form = $this->createForm(NewsForm::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($news);
            $entityManager->flush();

            return $this->redirectToRoute('app_news_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('news/new.html.twig', [
            'news' => $news,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_news_show', methods: ['GET'])]
    public function show(News $news): Response
    {
        return $this->render('news/show.html.twig', [
            'news' => $news,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_news_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, News $news, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(NewsForm::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_news_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('news/edit.html.twig', [
            'news' => $news,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_news_delete', methods: ['POST'])]
    public function delete(Request $request, News $news, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$news->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($news);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_news_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/news/_form.html.twig
<div class="form-wrapper">
  {{ form_start(form, {'action': action|default('')}) }}

    <div class="row">
      <div class="col-md-4 mb-3">
        {{ form_row(form.author) }}
      </div>
      <div class="col-md-4 mb-3">
        {{ form_row(form.title) }}
      </div>
      <div class="col-md-4 mb-3">
        {{ form_row(form.date_news) }}
      </div>
    </div>

    <div class="mb-3">
      {{ form_row(form.body) }}
    </div>
    <div class="mb-3">
      {{ form_row(form.link) }}
    </div>

    <div class="modal-footer">
      <button type="submit" class="btn btn-primary w-50" title="Save">
        <i class="fa fa-save"></i> Guardar
      </button>
      <button type="button" class="btn btn-secondary w-50" data-bs-dismiss="modal" title="Cancel">
        <i class="fa fa-times"></i> Cancelar
      </button>
    </div>



  {{ form_end(form) }}
</div>

templates/news/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit News{% endblock %}

{% block body %}

    {% include 'news/_form.html.twig' with {
    form: form,
    action: path('app_news_edit', {'id': news.id}),
    button_label: 'Actualizar'
    } %}


    

    
{% endblock %}

templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'News'|trans }}{% endblock %}

{% block body %}
  <h1>{{ 'News'|trans }}</h1>

  <div class="news-actions">
    <button type="button" class="table-button"
            title="{{ 'Add news'|trans }}"
            data-url="{{ path('app_news_new') }}"
            onclick="loadFormInModal(this)">
      <i class="fa fa-plus"></i>
    </button>


    <a href="{{ path('app_home') }}" class="table-button" title="{{ 'Home'|trans }}">
      <i class="fa fa-home"></i>
    </a>
  </div>

  <div class="table-wrapper">
    <table class="table styled-table">
      <thead>
        <tr>
          <th>{{ 'Actions'|trans }}</th>
          <th>{{ 'Author'|trans }}</th>
          <th>{{ 'Title'|trans }}</th>
          <th>{{ 'Date news'|trans }}</th>
          <th>{{ 'Body'|trans }}</th>
          <th>{{ 'Link'|trans }}</th>
          
        </tr>
      </thead>
      <tbody>
        {% for news in news %}
          <tr>
            <td class="actions-cell">
              <div class="action-buttons">
                <a href="#" class="table-button"
                  data-url="{{ path('app_news_edit', {'id': news.id}) }}"
                  onclick="loadFormInModal(this)"
                  title="{{ 'Edit'|trans }}">
                  <i class="fa fa-pencil"></i>
                </a>

                <form method="post" action="{{ path('app_news_delete', {'id': news.id}) }}" onsubmit="return confirm('¿Estás seguro de que quieres eliminar esta noticia?');">
                  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ news.id) }}">
                  <button class="table-button delete-button" title="Delete">
                    <i class="fa fa-trash"></i>
                  </button>
                </form>
              </div>
            </td>
            <td>{{ news.author }}</td>
            <td>{{ news.title }}</td>
            <td>{{ news.dateNews ? news.dateNews|date('d-m-Y') : '' }}</td>
            <td>{{ news.body|slice(0, 100) ~ '...' }}</td>
            <td>
              {% if news.link %}
                <a href="{{ news.link }}" target="_blank" rel="noopener noreferrer">
                  {{ news.link|slice(0, 40) ~ '...' }}
                </a>
              {% else %}
                -
              {% endif %}
            </td>
            
          </tr>
        {% else %}
          <tr>
            <td colspan="6">{{ 'No records found'|trans }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Modal para añadir noticia -->
<div class="modal fade" id="addNewsModal" tabindex="-1" aria-labelledby="addNewsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl custom-modal-width">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addNewsModalLabel">{{ 'Add News'|trans }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ 'Close'|trans }}"></button>
      </div>
      <div class="modal-body">
        {{ include('news/_form.html.twig', { form: form }) }}
      </div>
    </div>
  </div>
</div>

<script>
  function loadFormInModal(button) {
    const url = button.getAttribute('data-url');
    fetch(url)
      .then(response => response.text())
      .then(html => {
        const modalBody = document.querySelector('#addNewsModal .modal-body');
        const modalTitle = document.querySelector('#addNewsModalLabel');
        modalBody.innerHTML = html;
        modalTitle.textContent = button.title || 'Editar noticia';
        new bootstrap.Modal(document.getElementById('addNewsModal')).show();
      })
      .catch(error => {
        console.error('Error al cargar el formulario:', error);
      });
  }
</script>


{% endblock %}

templates/news/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New News{% endblock %}

{% block body %}

    {% include 'news/_form.html.twig' with {
    form: form,
    action: path('app_news_new'),
    button_label: 'Guardar'
    } %}


    
{% endblock %}